language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_script:
  - fmtRes="$(gofmt -s -l .)" bash -c '[ "$fmtRes" == "" ] || (echo -e "The following files did not pass gofmt -s:\n" "$fmtRes" && exit 1)'
